# This is a basic workflow

name: CI

# Controls when the action will run.
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checlout@v2

      - name: Run a one-line script
        run: echo Hello, world

      - name: Run a multi-line script
        run: 
          echo Add other actions to build,
          echo text, and desploy your project.
       
      
    
